import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const appJs = readFileSync(new URL("../../main/resources/web/console/app.js", import.meta.url), "utf8");

test("console runtime health avoids raw English metric and section labels", () => {
    assert.match(appJs, /overviewCard\("运行中", String\(activeRunCount\)\)/);
    assert.match(appJs, /overviewCard\("24h 失败", String\(failedRunCount\)\)/);
    assert.match(appJs, /overviewCard\("24h 崩溃", String\(crashedRunCount\)\)/);
    assert.match(appJs, /overviewCard\("不可用", String\(unavailableProviderCount\)\)/);
    assert.match(appJs, /overviewCard\("需认证", String\(authNeededProviderCount\)\)/);
    assert.match(appJs, /overviewCard\("平均耗时", averageDurationMs === null \? "暂无" : formatDurationMs\(averageDurationMs\)\)/);
    assert.match(appJs, />恢复窗口</);
    assert.match(appJs, />Provider 对比</);
    assert.match(appJs, />运行中任务</);
    assert.match(appJs, />最近失败</);
    assert.match(appJs, />Provider 问题</);
    assert.match(appJs, /认证：\$\{escapeHtml\(humanizeAuthStatusLabel\(authStatus\)\)\}/);
    assert.doesNotMatch(appJs, /overviewCard\("Active", String\(activeRunCount\)\)/);
    assert.doesNotMatch(appJs, /overviewCard\("Failed 24h"/);
    assert.doesNotMatch(appJs, /overviewCard\("Crashed 24h"/);
    assert.doesNotMatch(appJs, /overviewCard\("Unavailable"/);
    assert.doesNotMatch(appJs, /overviewCard\("Auth Needed"/);
    assert.doesNotMatch(appJs, /overviewCard\("Avg Duration"/);
    assert.doesNotMatch(appJs, />recovery window</);
    assert.doesNotMatch(appJs, />provider comparison</);
    assert.doesNotMatch(appJs, />active runs</);
    assert.doesNotMatch(appJs, />recent failures</);
    assert.doesNotMatch(appJs, />provider problems</);
});

test("console provider inventory and execution cards use operator Chinese labels", () => {
    assert.match(appJs, /"未知执行通道"/);
  assert.match(appJs, />暂无能力</);
    assert.match(appJs, /ready \? "就绪" : "未就绪"/);
    assert.match(appJs, /installed \? "已安装" : "缺失"/);
    assert.match(appJs, /认证：\$\{escapeHtml\(humanizeAuthStatusLabel\(authStatus\)\)\}/);
    assert.match(appJs, /版本：\$\{escapeHtml\(version\)\}/);
    assert.match(appJs, /检查：\$\{escapeHtml\(formatTime\(checkedAt\)\)\}/);
    assert.match(appJs, /providerReady \? "执行通道就绪" : "执行通道未就绪"/);
    assert.match(appJs, /overviewCard\("运行 ID", runId\)/);
    assert.match(appJs, /overviewCard\("开始时间", formatTime\(run\.started_at \|\| run\.startedAt\)\)/);
    assert.match(appJs, /overviewCard\("耗时", formatDurationMs\(run\.duration_ms \|\| run\.durationMs\)\)/);
    assert.match(appJs, /overviewCard\("产物数", String\(run\.artifact_count \|\| run\.artifactCount\)\)/);
    assert.match(appJs, /回退原因：\$\{escapeHtml\(preview\(fallbackReason, 180\)\)\}/);
    assert.match(appJs, /认证：\$\{escapeHtml\(humanizeAuthStatusLabel\(authStatus\)\)\}/);
    assert.match(appJs, /版本：\$\{escapeHtml\(providerVersion\)\}/);
    assert.match(appJs, />查看 Provider</);
    assert.match(appJs, />查看运行</);
    assert.match(appJs, />最近事件</);
    assert.match(appJs, />执行产物</);
    assert.match(appJs, /humanizeWorkerRoleLabel\(workerRole\)/);
    assert.match(appJs, /`执行方 \$\{selectedWorker\}`/);
    assert.doesNotMatch(appJs, /"unknown provider"/);
    assert.doesNotMatch(appJs, /"no capability"/);
    assert.doesNotMatch(appJs, /ready \? "ready" : "not ready"/);
    assert.doesNotMatch(appJs, /installed \? "installed" : "missing"/);
    assert.doesNotMatch(appJs, /providerReady \? "provider ready" : "provider not ready"/);
    assert.doesNotMatch(appJs, /overviewCard\("Run ID", runId\)/);
    assert.doesNotMatch(appJs, /overviewCard\("Started"/);
    assert.doesNotMatch(appJs, /overviewCard\("Duration"/);
    assert.doesNotMatch(appJs, /overviewCard\("Artifacts"/);
    assert.doesNotMatch(appJs, /Fallback:/);
    assert.doesNotMatch(appJs, /auth:/);
    assert.doesNotMatch(appJs, /version:/);
    assert.doesNotMatch(appJs, />View Provider</);
    assert.doesNotMatch(appJs, />View Run</);
    assert.doesNotMatch(appJs, />recent events</);
    assert.doesNotMatch(appJs, />agent artifacts</);
});

test("console provider detail and run detail avoid raw English diagnostics headings", () => {
    assert.match(appJs, />启动协议探测</);
    assert.match(appJs, /ok \? "探测通过" : "探测失败"/);
    assert.match(appJs, />协议推断</);
    assert.match(appJs, /解析器：\$\{escapeHtml\(suggestedParser\)\}/);
    assert.match(appJs, /overviewCard\("退出码", exitCode === null \? "暂无" : String\(exitCode\)\)/);
    assert.match(appJs, /overviewCard\("命令形态", commandShape\.length > 0 \? commandShape\.join\(" "\) : "暂无"\)/);
    assert.match(appJs, /overviewCard\("协议", firstNonBlank\(metadata\.provider_protocol, metadata\.providerProtocol, "未知"\)\)/);
    assert.match(appJs, /overviewCard\("解析提示", suggestedParser \|\| "暂无"\)/);
    assert.match(appJs, />Provider 预检结果</);
    assert.match(appJs, /ok \? "预检通过" : "预检失败"/);
    assert.match(appJs, /retryable \? "可重试" : "需人工处理"/);
    assert.match(appJs, /overviewCard\("探测参数", probeArgs\.length > 0 \? probeArgs\.join\(" "\) : "暂无"\)/);
    assert.match(appJs, /overviewCard\("检查时间", firstNonBlank\(agent\.checked_at, agent\.checkedAt\) \? formatTime\(firstNonBlank\(agent\.checked_at, agent\.checkedAt\)\) : "未知"\)/);
    assert.match(appJs, />执行方派发探测</);
    assert.match(appJs, /ready \? "派发就绪" : "派发阻塞"/);
    assert.match(appJs, /dispatchReady \? "预检通过" : "预检失败"/);
    assert.match(appJs, /providerRetryable \? "可重试" : "需人工处理"/);
    assert.match(appJs, /cached \? "缓存结果" : "最新探测"/);
    assert.match(appJs, /activeProbe \? "主动探测" : "被动回退"/);
    assert.match(appJs, /overviewCard\("执行方", workerId \|\| readiness\.worker_id \|\| readiness\.workerId \|\| "未分配"\)/);
    assert.match(appJs, /overviewCard\("启动方式", launchMode \|\| "未知"\)/);
    assert.match(appJs, /overviewCard\("最近运行", String\(recentRuns\.length\)\)/);
    assert.match(appJs, /overviewCard\("运行中", String\(providerActiveRunCount \?\? activeRuns\.length\)\)/);
    assert.match(appJs, /overviewCard\("已完成", String\(completedRuns\.length\)\)/);
    assert.match(appJs, /overviewCard\("失败", `\$\{failedRuns\.length\} \/ \$\{failureRate\}`\)/);
    assert.match(appJs, /overviewCard\("平均耗时", averageDurationMs === null \? "暂无" : formatDurationMs\(averageDurationMs\)\)/);
    assert.match(appJs, /overviewCard\("最近成功", lastSuccess \? formatTime\(lastSuccess\.started_at \|\| lastSuccess\.startedAt\) : "暂无"\)/);
    assert.match(appJs, />最近失败</);
    assert.match(appJs, /overviewCard\("任务", taskId \|\| "未知"\)/);
    assert.match(appJs, /overviewCard\("会话", sessionId \|\| "未知"\)/);
    assert.match(appJs, /overviewCard\("开始时间", formatTime\(run\.started_at \|\| run\.startedAt\)\)/);
    assert.match(appJs, /overviewCard\("耗时", durationMs === null \? "未知" : formatDurationMs\(durationMs\)\)/);
    assert.match(appJs, /overviewCard\("产物数", artifactCount === null \? String\(\(artifacts \|\| \[\]\)\.length\) : String\(artifactCount\)\)/);
    assert.match(appJs, /overviewCard\("最近事件", firstNonBlank\(run\.last_event_type, run\.lastEventType, "未知"\)\)/);
    assert.match(appJs, />运行时间线</);
    assert.match(appJs, />运行产物</);
    assert.doesNotMatch(appJs, />startup protocol probe</);
    assert.doesNotMatch(appJs, /ok \? "probe ok" : "probe failed"/);
    assert.doesNotMatch(appJs, />protocol inferred</);
    assert.doesNotMatch(appJs, /parser:/);
    assert.doesNotMatch(appJs, /overviewCard\("Exit Code"/);
    assert.doesNotMatch(appJs, /overviewCard\("Command Shape"/);
    assert.doesNotMatch(appJs, /overviewCard\("Protocol"/);
    assert.doesNotMatch(appJs, /overviewCard\("Parser Hint"/);
    assert.doesNotMatch(appJs, />provider preflight result</);
    assert.doesNotMatch(appJs, /ok \? "preflight ok" : "preflight failed"/);
    assert.doesNotMatch(appJs, /retryable \? "retryable" : "manual"/);
    assert.doesNotMatch(appJs, />worker dispatch probe</);
    assert.doesNotMatch(appJs, /ready \? "dispatch ready" : "dispatch blocked"/);
    assert.doesNotMatch(appJs, /dispatchReady \? "preflight ok" : "preflight failed"/);
    assert.doesNotMatch(appJs, /cached \? "cached" : "fresh probe"/);
    assert.doesNotMatch(appJs, /activeProbe \? "active probe" : "passive fallback"/);
    assert.doesNotMatch(appJs, />runtime diagnostics</);
    assert.doesNotMatch(appJs, /overviewCard\("Recent Runs"/);
    assert.doesNotMatch(appJs, /overviewCard\("Completed"/);
    assert.doesNotMatch(appJs, /overviewCard\("Last Success"/);
    assert.doesNotMatch(appJs, />last failure</);
    assert.doesNotMatch(appJs, /overviewCard\("Task"/);
    assert.doesNotMatch(appJs, /overviewCard\("Session"/);
    assert.doesNotMatch(appJs, /overviewCard\("Last Event"/);
    assert.doesNotMatch(appJs, />run timeline</);
    assert.doesNotMatch(appJs, />run artifacts</);
});
